apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | indent 4 }}

data:
  db-password: {{ .Values.db.password | b64enc }}