apiVersion: skaffold/v1
kind: Config
metadata:
  name: CHANGEMEPLEASE
build:
  artifacts:
  - image: app
    sync:
      manual:
      - src: 'src/**/*.py'
        dest: /app
        strip: src/
      - src: 'src/static/**'
        dest: /app
        strip: src/
      - src: 'src/templates/**'
        dest: /app
        strip: src/
#     this conflicts with local build usning docker cli
#     kaniko:
#       cache: {}
  tagPolicy:
    dateTime:
      format: 20060102-150405
# portForward: {}
deploy:
  # kustomize:
  #   path: .
  kubectl:
    manifests:
    - k8s/*
profiles:
- name: local
  activation:
  - env: KUBECONFIG=!
  build:
    local:
      useDockerCLI: false
      useBuildkit: false
  test:
  # we cannot do structure tests for incluster setup because
  # container-structure-test locally and skaffold doesn't do 'docker pull' after build
  - image: app
    structureTests:
    - ./test/*.yaml
- name: incluster
  build:
    cluster:
      dockerConfig:
        path: .hub/dockerconfig.json
