apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: CHANGEMEPLEASE
build:
  artifacts:
    # Set image name. During hub configure artifact repository will be added
  - image: asi-next-js
    sync:
      manual:
      - src: 'components/**/*.js'
        dest: /app/components
      - src: 'components/**/*.jsx'
        dest: /app/components
      - src: 'pages/**/*.js'
        dest: /app/pages
      - src: 'pages/**/*.jsx'
        dest: /app/pages
#     this conflicts with local build usning docker cli
#     kaniko:
#       cache: {}
  tagPolicy:
    dateTime:
      format: 20060102-150405
deploy:
  helm:
    releases:
    - name: asi-next-js
      chartPath: helm/
      valuesFiles:
      - helm/values.yaml
      version: 1.0.0
      skipBuildDependencies: true
      artifactOverrides:
        # Set image name. During hub configure artifact repository will be added
        image: asi-next-js # no tag present!
        # Skaffold continuously tags your image, so no need to put one here.
      setValues:
        ingress.host: $HUB_INGRESS_HOST
        ingress.tlsHost: $HUB_INGRESS_HOST
profiles:
- name: local
  activation:
  - env: KUBECONFIG=!
  build:
    local:
      useDockerCLI: false
      useBuildkit: false
  test:
  # we cannot do structure tests for kaniko setup because
  # container-structure-test locally and skaffold doesn't do 'docker pull' after build
  - image: asi-next-js
    structureTests:
    - ./test/*.yaml
- name: kaniko
  build:
    cluster:
      dockerConfig:
        path: .hub/dockerconfig.json
