apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: CHANGEMEPLEASE
build:
  artifacts:
    # Set image name. During hub configure artifact repository will be added
  - image: asi-next-js
    sync:
      infer:
      - "**/*.js"
      - "**/*jsx"
  tagPolicy:
    dateTime:
      format: 20060102-150405
deploy:
  helm:
    releases:
    - name: asi-next-js
      chartPath: helm/
      valuesFiles:
      - helm/values.yaml
      version: 1.0.0
      skipBuildDependencies: true
      artifactOverrides:
        # Set image name. During hub configure artifact repository will be added
        image: asi-next-js # no tag present!
        # Skaffold continuously tags your image, so no need to put one here.
      setValueTemplates:
        ingress.host: "{{.HUB_APP_HOST}}"
        ingress.tlsHost: "{{.HUB_APP_HOST}}"
        db.host: "{{.DB_HOST}}"
        db.port: "{{.DB_PORT}}"
        db.user: "{{.DB_USER}}"
        db.password: "{{.DB_PASSWORD}}"
        db.name: "{{.DB_NAME}}"
profiles:
- name: local
  activation:
  - env: KUBECONFIG=!
  patches:
  - op: add
    path: /build/artifacts/0/docker
    value:
      dockerfile: Dockerfile
      buildArgs:
        NPM_SCRIPT: 'dev'
- name: kaniko
  activation:
  - command: dev
  patches:
  - op: add
    path: /build/artifacts/0/kaniko
    value:
      cache: {}
      dockerfile: Dockerfile
      buildArgs:
        NPM_SCRIPT: 'dev'
  build:
    cluster:
      dockerConfig:
        path: .hub/dockerconfig.json
portForward:
- resourceType: Deployment
  resourceName: asi-next-js
  namespace: default
  port: 9229
  localPort: 9229
